runtime: python
env: flex
entrypoint: gunicorn -w 2 --timeout 120 --graceful-timeout 60 -b :$PORT app:app

runtime_config:
  python_version: 3.6
resources:
  cpu: 2
  memory_gb: 4
manual_scaling:
  instances: 1
